name: ocr-app
author: Tencent Cloud, Inc.
org: Tencent Cloud, Inc.
description: Deploy a serverless OCR application.
keywords: tencent, serverless, express, website, ocr
repo: https://github.com/serverless-components/tencent-ocr
readme: https://github.com/serverless-components/tencent-ocr/tree/master/README.md
license: MIT
src:
  src: ./
  exclude:
    - .env
    - serverless.yml
    - '**/node_modules'
    - '**/package-lock.json'
